Properly error out if we get a DOCTYPE (ie no CSV data)

diff --git a/fetchstats b/fetchstats
--- a/fetchstats
+++ b/fetchstats
@@ -81,6 +81,10 @@ while [ "yes" == "$GO" ] ; do
 			exit 2
 		fi
 		HEADING=`echo "$CSV" | head -n 1`
+		if [[ "$HEADING" == *DOCTYPE* ]]; then
+		    echo "Error retrieving data.  Date range may be outside of available data." >&2
+	        exit 2
+		fi
 	else
 		CSV=`echo "$CSV" | grep -v "$HEADING"`
 	fi
